// Code generated by go-swagger; DO NOT EDIT.

package labels

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPILabelsReader is a Reader for the GetAPILabels structure.
type GetAPILabelsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPILabelsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPILabelsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPILabelsOK creates a GetAPILabelsOK with default headers values
func NewGetAPILabelsOK() *GetAPILabelsOK {
	return &GetAPILabelsOK{}
}

/* GetAPILabelsOK describes a response with status code 200, with default header values.

Success
*/
type GetAPILabelsOK struct {
}

func (o *GetAPILabelsOK) Error() string {
	return fmt.Sprintf("[GET /api/Labels][%d] getApiLabelsOK ", 200)
}

func (o *GetAPILabelsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
