// Code generated by go-swagger; DO NOT EDIT.

package subdomains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPISubdomainsIDReader is a Reader for the DeleteAPISubdomainsID structure.
type DeleteAPISubdomainsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPISubdomainsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAPISubdomainsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAPISubdomainsIDOK creates a DeleteAPISubdomainsIDOK with default headers values
func NewDeleteAPISubdomainsIDOK() *DeleteAPISubdomainsIDOK {
	return &DeleteAPISubdomainsIDOK{}
}

/* DeleteAPISubdomainsIDOK describes a response with status code 200, with default header values.

Success
*/
type DeleteAPISubdomainsIDOK struct {
}

func (o *DeleteAPISubdomainsIDOK) Error() string {
	return fmt.Sprintf("[DELETE /api/Subdomains/{id}][%d] deleteApiSubdomainsIdOK ", 200)
}

func (o *DeleteAPISubdomainsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
