// Code generated by go-swagger; DO NOT EDIT.

package subdomains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPISubdomainsIDParams creates a new DeleteAPISubdomainsIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPISubdomainsIDParams() *DeleteAPISubdomainsIDParams {
	return &DeleteAPISubdomainsIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPISubdomainsIDParamsWithTimeout creates a new DeleteAPISubdomainsIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPISubdomainsIDParamsWithTimeout(timeout time.Duration) *DeleteAPISubdomainsIDParams {
	return &DeleteAPISubdomainsIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPISubdomainsIDParamsWithContext creates a new DeleteAPISubdomainsIDParams object
// with the ability to set a context for a request.
func NewDeleteAPISubdomainsIDParamsWithContext(ctx context.Context) *DeleteAPISubdomainsIDParams {
	return &DeleteAPISubdomainsIDParams{
		Context: ctx,
	}
}

// NewDeleteAPISubdomainsIDParamsWithHTTPClient creates a new DeleteAPISubdomainsIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPISubdomainsIDParamsWithHTTPClient(client *http.Client) *DeleteAPISubdomainsIDParams {
	return &DeleteAPISubdomainsIDParams{
		HTTPClient: client,
	}
}

/* DeleteAPISubdomainsIDParams contains all the parameters to send to the API endpoint
   for the delete API subdomains ID operation.

   Typically these are written to a http.Request.
*/
type DeleteAPISubdomainsIDParams struct {

	// ID.
	//
	// Format: uuid
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API subdomains ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPISubdomainsIDParams) WithDefaults() *DeleteAPISubdomainsIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API subdomains ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPISubdomainsIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API subdomains ID params
func (o *DeleteAPISubdomainsIDParams) WithTimeout(timeout time.Duration) *DeleteAPISubdomainsIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API subdomains ID params
func (o *DeleteAPISubdomainsIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API subdomains ID params
func (o *DeleteAPISubdomainsIDParams) WithContext(ctx context.Context) *DeleteAPISubdomainsIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API subdomains ID params
func (o *DeleteAPISubdomainsIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API subdomains ID params
func (o *DeleteAPISubdomainsIDParams) WithHTTPClient(client *http.Client) *DeleteAPISubdomainsIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API subdomains ID params
func (o *DeleteAPISubdomainsIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete API subdomains ID params
func (o *DeleteAPISubdomainsIDParams) WithID(id strfmt.UUID) *DeleteAPISubdomainsIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete API subdomains ID params
func (o *DeleteAPISubdomainsIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPISubdomainsIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
