// Code generated by go-swagger; DO NOT EDIT.

package subdomains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPISubdomainsGetPaginateTargetNameRootDomainNameReader is a Reader for the GetAPISubdomainsGetPaginateTargetNameRootDomainName structure.
type GetAPISubdomainsGetPaginateTargetNameRootDomainNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPISubdomainsGetPaginateTargetNameRootDomainNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPISubdomainsGetPaginateTargetNameRootDomainNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPISubdomainsGetPaginateTargetNameRootDomainNameOK creates a GetAPISubdomainsGetPaginateTargetNameRootDomainNameOK with default headers values
func NewGetAPISubdomainsGetPaginateTargetNameRootDomainNameOK() *GetAPISubdomainsGetPaginateTargetNameRootDomainNameOK {
	return &GetAPISubdomainsGetPaginateTargetNameRootDomainNameOK{}
}

/* GetAPISubdomainsGetPaginateTargetNameRootDomainNameOK describes a response with status code 200, with default header values.

Success
*/
type GetAPISubdomainsGetPaginateTargetNameRootDomainNameOK struct {
}

func (o *GetAPISubdomainsGetPaginateTargetNameRootDomainNameOK) Error() string {
	return fmt.Sprintf("[GET /api/Subdomains/GetPaginate/{targetName}/{rootDomainName}][%d] getApiSubdomainsGetPaginateTargetNameRootDomainNameOK ", 200)
}

func (o *GetAPISubdomainsGetPaginateTargetNameRootDomainNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
