// Code generated by go-swagger; DO NOT EDIT.

package subdomains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPISubdomainsTargetNameRootDomainNameSubdomainNameReader is a Reader for the GetAPISubdomainsTargetNameRootDomainNameSubdomainName structure.
type GetAPISubdomainsTargetNameRootDomainNameSubdomainNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPISubdomainsTargetNameRootDomainNameSubdomainNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPISubdomainsTargetNameRootDomainNameSubdomainNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPISubdomainsTargetNameRootDomainNameSubdomainNameOK creates a GetAPISubdomainsTargetNameRootDomainNameSubdomainNameOK with default headers values
func NewGetAPISubdomainsTargetNameRootDomainNameSubdomainNameOK() *GetAPISubdomainsTargetNameRootDomainNameSubdomainNameOK {
	return &GetAPISubdomainsTargetNameRootDomainNameSubdomainNameOK{}
}

/* GetAPISubdomainsTargetNameRootDomainNameSubdomainNameOK describes a response with status code 200, with default header values.

Success
*/
type GetAPISubdomainsTargetNameRootDomainNameSubdomainNameOK struct {
}

func (o *GetAPISubdomainsTargetNameRootDomainNameSubdomainNameOK) Error() string {
	return fmt.Sprintf("[GET /api/Subdomains/{targetName}/{rootDomainName}/{subdomainName}][%d] getApiSubdomainsTargetNameRootDomainNameSubdomainNameOK ", 200)
}

func (o *GetAPISubdomainsTargetNameRootDomainNameSubdomainNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
