// Code generated by go-swagger; DO NOT EDIT.

package subdomains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hiddengearz/reconness-cli/sdk/models"
)

// NewPostAPISubdomainsParams creates a new PostAPISubdomainsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPISubdomainsParams() *PostAPISubdomainsParams {
	return &PostAPISubdomainsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPISubdomainsParamsWithTimeout creates a new PostAPISubdomainsParams object
// with the ability to set a timeout on a request.
func NewPostAPISubdomainsParamsWithTimeout(timeout time.Duration) *PostAPISubdomainsParams {
	return &PostAPISubdomainsParams{
		timeout: timeout,
	}
}

// NewPostAPISubdomainsParamsWithContext creates a new PostAPISubdomainsParams object
// with the ability to set a context for a request.
func NewPostAPISubdomainsParamsWithContext(ctx context.Context) *PostAPISubdomainsParams {
	return &PostAPISubdomainsParams{
		Context: ctx,
	}
}

// NewPostAPISubdomainsParamsWithHTTPClient creates a new PostAPISubdomainsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPISubdomainsParamsWithHTTPClient(client *http.Client) *PostAPISubdomainsParams {
	return &PostAPISubdomainsParams{
		HTTPClient: client,
	}
}

/* PostAPISubdomainsParams contains all the parameters to send to the API endpoint
   for the post API subdomains operation.

   Typically these are written to a http.Request.
*/
type PostAPISubdomainsParams struct {

	// Body.
	Body *models.SubdomainDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API subdomains params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPISubdomainsParams) WithDefaults() *PostAPISubdomainsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API subdomains params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPISubdomainsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API subdomains params
func (o *PostAPISubdomainsParams) WithTimeout(timeout time.Duration) *PostAPISubdomainsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API subdomains params
func (o *PostAPISubdomainsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API subdomains params
func (o *PostAPISubdomainsParams) WithContext(ctx context.Context) *PostAPISubdomainsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API subdomains params
func (o *PostAPISubdomainsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API subdomains params
func (o *PostAPISubdomainsParams) WithHTTPClient(client *http.Client) *PostAPISubdomainsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API subdomains params
func (o *PostAPISubdomainsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API subdomains params
func (o *PostAPISubdomainsParams) WithBody(body *models.SubdomainDto) *PostAPISubdomainsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API subdomains params
func (o *PostAPISubdomainsParams) SetBody(body *models.SubdomainDto) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPISubdomainsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
