// Code generated by go-swagger; DO NOT EDIT.

package subdomains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutAPISubdomainsIDReader is a Reader for the PutAPISubdomainsID structure.
type PutAPISubdomainsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPISubdomainsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPISubdomainsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutAPISubdomainsIDOK creates a PutAPISubdomainsIDOK with default headers values
func NewPutAPISubdomainsIDOK() *PutAPISubdomainsIDOK {
	return &PutAPISubdomainsIDOK{}
}

/* PutAPISubdomainsIDOK describes a response with status code 200, with default header values.

Success
*/
type PutAPISubdomainsIDOK struct {
}

func (o *PutAPISubdomainsIDOK) Error() string {
	return fmt.Sprintf("[PUT /api/Subdomains/{id}][%d] putApiSubdomainsIdOK ", 200)
}

func (o *PutAPISubdomainsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
