// Code generated by go-swagger; DO NOT EDIT.

package subdomains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hiddengearz/reconness-cli/sdk/models"
)

// NewPutAPISubdomainsLabelIDParams creates a new PutAPISubdomainsLabelIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPISubdomainsLabelIDParams() *PutAPISubdomainsLabelIDParams {
	return &PutAPISubdomainsLabelIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPISubdomainsLabelIDParamsWithTimeout creates a new PutAPISubdomainsLabelIDParams object
// with the ability to set a timeout on a request.
func NewPutAPISubdomainsLabelIDParamsWithTimeout(timeout time.Duration) *PutAPISubdomainsLabelIDParams {
	return &PutAPISubdomainsLabelIDParams{
		timeout: timeout,
	}
}

// NewPutAPISubdomainsLabelIDParamsWithContext creates a new PutAPISubdomainsLabelIDParams object
// with the ability to set a context for a request.
func NewPutAPISubdomainsLabelIDParamsWithContext(ctx context.Context) *PutAPISubdomainsLabelIDParams {
	return &PutAPISubdomainsLabelIDParams{
		Context: ctx,
	}
}

// NewPutAPISubdomainsLabelIDParamsWithHTTPClient creates a new PutAPISubdomainsLabelIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPISubdomainsLabelIDParamsWithHTTPClient(client *http.Client) *PutAPISubdomainsLabelIDParams {
	return &PutAPISubdomainsLabelIDParams{
		HTTPClient: client,
	}
}

/* PutAPISubdomainsLabelIDParams contains all the parameters to send to the API endpoint
   for the put API subdomains label ID operation.

   Typically these are written to a http.Request.
*/
type PutAPISubdomainsLabelIDParams struct {

	// Body.
	Body *models.SubdomainLabelDto

	// ID.
	//
	// Format: uuid
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put API subdomains label ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPISubdomainsLabelIDParams) WithDefaults() *PutAPISubdomainsLabelIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API subdomains label ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPISubdomainsLabelIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API subdomains label ID params
func (o *PutAPISubdomainsLabelIDParams) WithTimeout(timeout time.Duration) *PutAPISubdomainsLabelIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API subdomains label ID params
func (o *PutAPISubdomainsLabelIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API subdomains label ID params
func (o *PutAPISubdomainsLabelIDParams) WithContext(ctx context.Context) *PutAPISubdomainsLabelIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API subdomains label ID params
func (o *PutAPISubdomainsLabelIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API subdomains label ID params
func (o *PutAPISubdomainsLabelIDParams) WithHTTPClient(client *http.Client) *PutAPISubdomainsLabelIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API subdomains label ID params
func (o *PutAPISubdomainsLabelIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put API subdomains label ID params
func (o *PutAPISubdomainsLabelIDParams) WithBody(body *models.SubdomainLabelDto) *PutAPISubdomainsLabelIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put API subdomains label ID params
func (o *PutAPISubdomainsLabelIDParams) SetBody(body *models.SubdomainLabelDto) {
	o.Body = body
}

// WithID adds the id to the put API subdomains label ID params
func (o *PutAPISubdomainsLabelIDParams) WithID(id strfmt.UUID) *PutAPISubdomainsLabelIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put API subdomains label ID params
func (o *PutAPISubdomainsLabelIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPISubdomainsLabelIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
