// Code generated by go-swagger; DO NOT EDIT.

package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hiddengearz/reconness-cli/sdk/models"
)

// NewPostAPINotesRootdomainTargetNameRootDomainNameParams creates a new PostAPINotesRootdomainTargetNameRootDomainNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPINotesRootdomainTargetNameRootDomainNameParams() *PostAPINotesRootdomainTargetNameRootDomainNameParams {
	return &PostAPINotesRootdomainTargetNameRootDomainNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPINotesRootdomainTargetNameRootDomainNameParamsWithTimeout creates a new PostAPINotesRootdomainTargetNameRootDomainNameParams object
// with the ability to set a timeout on a request.
func NewPostAPINotesRootdomainTargetNameRootDomainNameParamsWithTimeout(timeout time.Duration) *PostAPINotesRootdomainTargetNameRootDomainNameParams {
	return &PostAPINotesRootdomainTargetNameRootDomainNameParams{
		timeout: timeout,
	}
}

// NewPostAPINotesRootdomainTargetNameRootDomainNameParamsWithContext creates a new PostAPINotesRootdomainTargetNameRootDomainNameParams object
// with the ability to set a context for a request.
func NewPostAPINotesRootdomainTargetNameRootDomainNameParamsWithContext(ctx context.Context) *PostAPINotesRootdomainTargetNameRootDomainNameParams {
	return &PostAPINotesRootdomainTargetNameRootDomainNameParams{
		Context: ctx,
	}
}

// NewPostAPINotesRootdomainTargetNameRootDomainNameParamsWithHTTPClient creates a new PostAPINotesRootdomainTargetNameRootDomainNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPINotesRootdomainTargetNameRootDomainNameParamsWithHTTPClient(client *http.Client) *PostAPINotesRootdomainTargetNameRootDomainNameParams {
	return &PostAPINotesRootdomainTargetNameRootDomainNameParams{
		HTTPClient: client,
	}
}

/* PostAPINotesRootdomainTargetNameRootDomainNameParams contains all the parameters to send to the API endpoint
   for the post API notes rootdomain target name root domain name operation.

   Typically these are written to a http.Request.
*/
type PostAPINotesRootdomainTargetNameRootDomainNameParams struct {

	// Body.
	Body *models.NoteDto

	// RootDomainName.
	RootDomainName string

	// TargetName.
	TargetName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API notes rootdomain target name root domain name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPINotesRootdomainTargetNameRootDomainNameParams) WithDefaults() *PostAPINotesRootdomainTargetNameRootDomainNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API notes rootdomain target name root domain name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPINotesRootdomainTargetNameRootDomainNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API notes rootdomain target name root domain name params
func (o *PostAPINotesRootdomainTargetNameRootDomainNameParams) WithTimeout(timeout time.Duration) *PostAPINotesRootdomainTargetNameRootDomainNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API notes rootdomain target name root domain name params
func (o *PostAPINotesRootdomainTargetNameRootDomainNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API notes rootdomain target name root domain name params
func (o *PostAPINotesRootdomainTargetNameRootDomainNameParams) WithContext(ctx context.Context) *PostAPINotesRootdomainTargetNameRootDomainNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API notes rootdomain target name root domain name params
func (o *PostAPINotesRootdomainTargetNameRootDomainNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API notes rootdomain target name root domain name params
func (o *PostAPINotesRootdomainTargetNameRootDomainNameParams) WithHTTPClient(client *http.Client) *PostAPINotesRootdomainTargetNameRootDomainNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API notes rootdomain target name root domain name params
func (o *PostAPINotesRootdomainTargetNameRootDomainNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API notes rootdomain target name root domain name params
func (o *PostAPINotesRootdomainTargetNameRootDomainNameParams) WithBody(body *models.NoteDto) *PostAPINotesRootdomainTargetNameRootDomainNameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API notes rootdomain target name root domain name params
func (o *PostAPINotesRootdomainTargetNameRootDomainNameParams) SetBody(body *models.NoteDto) {
	o.Body = body
}

// WithRootDomainName adds the rootDomainName to the post API notes rootdomain target name root domain name params
func (o *PostAPINotesRootdomainTargetNameRootDomainNameParams) WithRootDomainName(rootDomainName string) *PostAPINotesRootdomainTargetNameRootDomainNameParams {
	o.SetRootDomainName(rootDomainName)
	return o
}

// SetRootDomainName adds the rootDomainName to the post API notes rootdomain target name root domain name params
func (o *PostAPINotesRootdomainTargetNameRootDomainNameParams) SetRootDomainName(rootDomainName string) {
	o.RootDomainName = rootDomainName
}

// WithTargetName adds the targetName to the post API notes rootdomain target name root domain name params
func (o *PostAPINotesRootdomainTargetNameRootDomainNameParams) WithTargetName(targetName string) *PostAPINotesRootdomainTargetNameRootDomainNameParams {
	o.SetTargetName(targetName)
	return o
}

// SetTargetName adds the targetName to the post API notes rootdomain target name root domain name params
func (o *PostAPINotesRootdomainTargetNameRootDomainNameParams) SetTargetName(targetName string) {
	o.TargetName = targetName
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPINotesRootdomainTargetNameRootDomainNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param rootDomainName
	if err := r.SetPathParam("rootDomainName", o.RootDomainName); err != nil {
		return err
	}

	// path param targetName
	if err := r.SetPathParam("targetName", o.TargetName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
