// Code generated by go-swagger; DO NOT EDIT.

package notes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostAPINotesRootdomainTargetNameRootDomainNameReader is a Reader for the PostAPINotesRootdomainTargetNameRootDomainName structure.
type PostAPINotesRootdomainTargetNameRootDomainNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPINotesRootdomainTargetNameRootDomainNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPINotesRootdomainTargetNameRootDomainNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPINotesRootdomainTargetNameRootDomainNameOK creates a PostAPINotesRootdomainTargetNameRootDomainNameOK with default headers values
func NewPostAPINotesRootdomainTargetNameRootDomainNameOK() *PostAPINotesRootdomainTargetNameRootDomainNameOK {
	return &PostAPINotesRootdomainTargetNameRootDomainNameOK{}
}

/* PostAPINotesRootdomainTargetNameRootDomainNameOK describes a response with status code 200, with default header values.

Success
*/
type PostAPINotesRootdomainTargetNameRootDomainNameOK struct {
}

func (o *PostAPINotesRootdomainTargetNameRootDomainNameOK) Error() string {
	return fmt.Sprintf("[POST /api/Notes/rootdomain/{targetName}/{rootDomainName}][%d] postApiNotesRootdomainTargetNameRootDomainNameOK ", 200)
}

func (o *PostAPINotesRootdomainTargetNameRootDomainNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
