// Code generated by go-swagger; DO NOT EDIT.

package categories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPICategoriesReader is a Reader for the GetAPICategories structure.
type GetAPICategoriesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPICategoriesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPICategoriesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPICategoriesOK creates a GetAPICategoriesOK with default headers values
func NewGetAPICategoriesOK() *GetAPICategoriesOK {
	return &GetAPICategoriesOK{}
}

/* GetAPICategoriesOK describes a response with status code 200, with default header values.

Success
*/
type GetAPICategoriesOK struct {
}

func (o *GetAPICategoriesOK) Error() string {
	return fmt.Sprintf("[GET /api/Categories][%d] getApiCategoriesOK ", 200)
}

func (o *GetAPICategoriesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
