// Code generated by go-swagger; DO NOT EDIT.

package root_domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams creates a new DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams() *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams {
	return &DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParamsWithTimeout creates a new DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParamsWithTimeout(timeout time.Duration) *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams {
	return &DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams{
		timeout: timeout,
	}
}

// NewDeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParamsWithContext creates a new DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams object
// with the ability to set a context for a request.
func NewDeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParamsWithContext(ctx context.Context) *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams {
	return &DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams{
		Context: ctx,
	}
}

// NewDeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParamsWithHTTPClient creates a new DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParamsWithHTTPClient(client *http.Client) *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams {
	return &DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams{
		HTTPClient: client,
	}
}

/* DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams contains all the parameters to send to the API endpoint
   for the delete API root domains delete subdomians target name root domain name operation.

   Typically these are written to a http.Request.
*/
type DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams struct {

	// RootDomainName.
	RootDomainName string

	// TargetName.
	TargetName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API root domains delete subdomians target name root domain name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams) WithDefaults() *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API root domains delete subdomians target name root domain name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API root domains delete subdomians target name root domain name params
func (o *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams) WithTimeout(timeout time.Duration) *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API root domains delete subdomians target name root domain name params
func (o *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API root domains delete subdomians target name root domain name params
func (o *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams) WithContext(ctx context.Context) *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API root domains delete subdomians target name root domain name params
func (o *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API root domains delete subdomians target name root domain name params
func (o *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams) WithHTTPClient(client *http.Client) *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API root domains delete subdomians target name root domain name params
func (o *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRootDomainName adds the rootDomainName to the delete API root domains delete subdomians target name root domain name params
func (o *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams) WithRootDomainName(rootDomainName string) *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams {
	o.SetRootDomainName(rootDomainName)
	return o
}

// SetRootDomainName adds the rootDomainName to the delete API root domains delete subdomians target name root domain name params
func (o *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams) SetRootDomainName(rootDomainName string) {
	o.RootDomainName = rootDomainName
}

// WithTargetName adds the targetName to the delete API root domains delete subdomians target name root domain name params
func (o *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams) WithTargetName(targetName string) *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams {
	o.SetTargetName(targetName)
	return o
}

// SetTargetName adds the targetName to the delete API root domains delete subdomians target name root domain name params
func (o *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams) SetTargetName(targetName string) {
	o.TargetName = targetName
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param rootDomainName
	if err := r.SetPathParam("rootDomainName", o.RootDomainName); err != nil {
		return err
	}

	// path param targetName
	if err := r.SetPathParam("targetName", o.TargetName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
