// Code generated by go-swagger; DO NOT EDIT.

package root_domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameReader is a Reader for the DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainName structure.
type DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameOK creates a DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameOK with default headers values
func NewDeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameOK() *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameOK {
	return &DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameOK{}
}

/* DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameOK describes a response with status code 200, with default header values.

Success
*/
type DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameOK struct {
}

func (o *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameOK) Error() string {
	return fmt.Sprintf("[DELETE /api/RootDomains/deleteSubdomians/{targetName}/{rootDomainName}][%d] deleteApiRootDomainsDeleteSubdomiansTargetNameRootDomainNameOK ", 200)
}

func (o *DeleteAPIRootDomainsDeleteSubdomiansTargetNameRootDomainNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
