// Code generated by go-swagger; DO NOT EDIT.

package root_domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIRootDomainsTargetNameRootDomainNameParams creates a new GetAPIRootDomainsTargetNameRootDomainNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIRootDomainsTargetNameRootDomainNameParams() *GetAPIRootDomainsTargetNameRootDomainNameParams {
	return &GetAPIRootDomainsTargetNameRootDomainNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIRootDomainsTargetNameRootDomainNameParamsWithTimeout creates a new GetAPIRootDomainsTargetNameRootDomainNameParams object
// with the ability to set a timeout on a request.
func NewGetAPIRootDomainsTargetNameRootDomainNameParamsWithTimeout(timeout time.Duration) *GetAPIRootDomainsTargetNameRootDomainNameParams {
	return &GetAPIRootDomainsTargetNameRootDomainNameParams{
		timeout: timeout,
	}
}

// NewGetAPIRootDomainsTargetNameRootDomainNameParamsWithContext creates a new GetAPIRootDomainsTargetNameRootDomainNameParams object
// with the ability to set a context for a request.
func NewGetAPIRootDomainsTargetNameRootDomainNameParamsWithContext(ctx context.Context) *GetAPIRootDomainsTargetNameRootDomainNameParams {
	return &GetAPIRootDomainsTargetNameRootDomainNameParams{
		Context: ctx,
	}
}

// NewGetAPIRootDomainsTargetNameRootDomainNameParamsWithHTTPClient creates a new GetAPIRootDomainsTargetNameRootDomainNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIRootDomainsTargetNameRootDomainNameParamsWithHTTPClient(client *http.Client) *GetAPIRootDomainsTargetNameRootDomainNameParams {
	return &GetAPIRootDomainsTargetNameRootDomainNameParams{
		HTTPClient: client,
	}
}

/* GetAPIRootDomainsTargetNameRootDomainNameParams contains all the parameters to send to the API endpoint
   for the get API root domains target name root domain name operation.

   Typically these are written to a http.Request.
*/
type GetAPIRootDomainsTargetNameRootDomainNameParams struct {

	// RootDomainName.
	RootDomainName string

	// TargetName.
	TargetName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API root domains target name root domain name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIRootDomainsTargetNameRootDomainNameParams) WithDefaults() *GetAPIRootDomainsTargetNameRootDomainNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API root domains target name root domain name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIRootDomainsTargetNameRootDomainNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API root domains target name root domain name params
func (o *GetAPIRootDomainsTargetNameRootDomainNameParams) WithTimeout(timeout time.Duration) *GetAPIRootDomainsTargetNameRootDomainNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API root domains target name root domain name params
func (o *GetAPIRootDomainsTargetNameRootDomainNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API root domains target name root domain name params
func (o *GetAPIRootDomainsTargetNameRootDomainNameParams) WithContext(ctx context.Context) *GetAPIRootDomainsTargetNameRootDomainNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API root domains target name root domain name params
func (o *GetAPIRootDomainsTargetNameRootDomainNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API root domains target name root domain name params
func (o *GetAPIRootDomainsTargetNameRootDomainNameParams) WithHTTPClient(client *http.Client) *GetAPIRootDomainsTargetNameRootDomainNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API root domains target name root domain name params
func (o *GetAPIRootDomainsTargetNameRootDomainNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRootDomainName adds the rootDomainName to the get API root domains target name root domain name params
func (o *GetAPIRootDomainsTargetNameRootDomainNameParams) WithRootDomainName(rootDomainName string) *GetAPIRootDomainsTargetNameRootDomainNameParams {
	o.SetRootDomainName(rootDomainName)
	return o
}

// SetRootDomainName adds the rootDomainName to the get API root domains target name root domain name params
func (o *GetAPIRootDomainsTargetNameRootDomainNameParams) SetRootDomainName(rootDomainName string) {
	o.RootDomainName = rootDomainName
}

// WithTargetName adds the targetName to the get API root domains target name root domain name params
func (o *GetAPIRootDomainsTargetNameRootDomainNameParams) WithTargetName(targetName string) *GetAPIRootDomainsTargetNameRootDomainNameParams {
	o.SetTargetName(targetName)
	return o
}

// SetTargetName adds the targetName to the get API root domains target name root domain name params
func (o *GetAPIRootDomainsTargetNameRootDomainNameParams) SetTargetName(targetName string) {
	o.TargetName = targetName
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIRootDomainsTargetNameRootDomainNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param rootDomainName
	if err := r.SetPathParam("rootDomainName", o.RootDomainName); err != nil {
		return err
	}

	// path param targetName
	if err := r.SetPathParam("targetName", o.TargetName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
