// Code generated by go-swagger; DO NOT EDIT.

package root_domains

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostAPIRootDomainsExportTargetNameRootDomainNameParams creates a new PostAPIRootDomainsExportTargetNameRootDomainNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIRootDomainsExportTargetNameRootDomainNameParams() *PostAPIRootDomainsExportTargetNameRootDomainNameParams {
	return &PostAPIRootDomainsExportTargetNameRootDomainNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIRootDomainsExportTargetNameRootDomainNameParamsWithTimeout creates a new PostAPIRootDomainsExportTargetNameRootDomainNameParams object
// with the ability to set a timeout on a request.
func NewPostAPIRootDomainsExportTargetNameRootDomainNameParamsWithTimeout(timeout time.Duration) *PostAPIRootDomainsExportTargetNameRootDomainNameParams {
	return &PostAPIRootDomainsExportTargetNameRootDomainNameParams{
		timeout: timeout,
	}
}

// NewPostAPIRootDomainsExportTargetNameRootDomainNameParamsWithContext creates a new PostAPIRootDomainsExportTargetNameRootDomainNameParams object
// with the ability to set a context for a request.
func NewPostAPIRootDomainsExportTargetNameRootDomainNameParamsWithContext(ctx context.Context) *PostAPIRootDomainsExportTargetNameRootDomainNameParams {
	return &PostAPIRootDomainsExportTargetNameRootDomainNameParams{
		Context: ctx,
	}
}

// NewPostAPIRootDomainsExportTargetNameRootDomainNameParamsWithHTTPClient creates a new PostAPIRootDomainsExportTargetNameRootDomainNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIRootDomainsExportTargetNameRootDomainNameParamsWithHTTPClient(client *http.Client) *PostAPIRootDomainsExportTargetNameRootDomainNameParams {
	return &PostAPIRootDomainsExportTargetNameRootDomainNameParams{
		HTTPClient: client,
	}
}

/* PostAPIRootDomainsExportTargetNameRootDomainNameParams contains all the parameters to send to the API endpoint
   for the post API root domains export target name root domain name operation.

   Typically these are written to a http.Request.
*/
type PostAPIRootDomainsExportTargetNameRootDomainNameParams struct {

	// RootDomainName.
	RootDomainName string

	// TargetName.
	TargetName string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API root domains export target name root domain name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIRootDomainsExportTargetNameRootDomainNameParams) WithDefaults() *PostAPIRootDomainsExportTargetNameRootDomainNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API root domains export target name root domain name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIRootDomainsExportTargetNameRootDomainNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API root domains export target name root domain name params
func (o *PostAPIRootDomainsExportTargetNameRootDomainNameParams) WithTimeout(timeout time.Duration) *PostAPIRootDomainsExportTargetNameRootDomainNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API root domains export target name root domain name params
func (o *PostAPIRootDomainsExportTargetNameRootDomainNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API root domains export target name root domain name params
func (o *PostAPIRootDomainsExportTargetNameRootDomainNameParams) WithContext(ctx context.Context) *PostAPIRootDomainsExportTargetNameRootDomainNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API root domains export target name root domain name params
func (o *PostAPIRootDomainsExportTargetNameRootDomainNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API root domains export target name root domain name params
func (o *PostAPIRootDomainsExportTargetNameRootDomainNameParams) WithHTTPClient(client *http.Client) *PostAPIRootDomainsExportTargetNameRootDomainNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API root domains export target name root domain name params
func (o *PostAPIRootDomainsExportTargetNameRootDomainNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRootDomainName adds the rootDomainName to the post API root domains export target name root domain name params
func (o *PostAPIRootDomainsExportTargetNameRootDomainNameParams) WithRootDomainName(rootDomainName string) *PostAPIRootDomainsExportTargetNameRootDomainNameParams {
	o.SetRootDomainName(rootDomainName)
	return o
}

// SetRootDomainName adds the rootDomainName to the post API root domains export target name root domain name params
func (o *PostAPIRootDomainsExportTargetNameRootDomainNameParams) SetRootDomainName(rootDomainName string) {
	o.RootDomainName = rootDomainName
}

// WithTargetName adds the targetName to the post API root domains export target name root domain name params
func (o *PostAPIRootDomainsExportTargetNameRootDomainNameParams) WithTargetName(targetName string) *PostAPIRootDomainsExportTargetNameRootDomainNameParams {
	o.SetTargetName(targetName)
	return o
}

// SetTargetName adds the targetName to the post API root domains export target name root domain name params
func (o *PostAPIRootDomainsExportTargetNameRootDomainNameParams) SetTargetName(targetName string) {
	o.TargetName = targetName
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIRootDomainsExportTargetNameRootDomainNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param rootDomainName
	if err := r.SetPathParam("rootDomainName", o.RootDomainName); err != nil {
		return err
	}

	// path param targetName
	if err := r.SetPathParam("targetName", o.TargetName); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
