// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIAgentsParams creates a new GetAPIAgentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIAgentsParams() *GetAPIAgentsParams {
	return &GetAPIAgentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIAgentsParamsWithTimeout creates a new GetAPIAgentsParams object
// with the ability to set a timeout on a request.
func NewGetAPIAgentsParamsWithTimeout(timeout time.Duration) *GetAPIAgentsParams {
	return &GetAPIAgentsParams{
		timeout: timeout,
	}
}

// NewGetAPIAgentsParamsWithContext creates a new GetAPIAgentsParams object
// with the ability to set a context for a request.
func NewGetAPIAgentsParamsWithContext(ctx context.Context) *GetAPIAgentsParams {
	return &GetAPIAgentsParams{
		Context: ctx,
	}
}

// NewGetAPIAgentsParamsWithHTTPClient creates a new GetAPIAgentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIAgentsParamsWithHTTPClient(client *http.Client) *GetAPIAgentsParams {
	return &GetAPIAgentsParams{
		HTTPClient: client,
	}
}

/* GetAPIAgentsParams contains all the parameters to send to the API endpoint
   for the get API agents operation.

   Typically these are written to a http.Request.
*/
type GetAPIAgentsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API agents params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIAgentsParams) WithDefaults() *GetAPIAgentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API agents params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIAgentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API agents params
func (o *GetAPIAgentsParams) WithTimeout(timeout time.Duration) *GetAPIAgentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API agents params
func (o *GetAPIAgentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API agents params
func (o *GetAPIAgentsParams) WithContext(ctx context.Context) *GetAPIAgentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API agents params
func (o *GetAPIAgentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API agents params
func (o *GetAPIAgentsParams) WithHTTPClient(client *http.Client) *GetAPIAgentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API agents params
func (o *GetAPIAgentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIAgentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
