// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIAgentsRunningTargetNameRootDomainNameSubdomainNameReader is a Reader for the GetAPIAgentsRunningTargetNameRootDomainNameSubdomainName structure.
type GetAPIAgentsRunningTargetNameRootDomainNameSubdomainNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIAgentsRunningTargetNameRootDomainNameSubdomainNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIAgentsRunningTargetNameRootDomainNameSubdomainNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIAgentsRunningTargetNameRootDomainNameSubdomainNameOK creates a GetAPIAgentsRunningTargetNameRootDomainNameSubdomainNameOK with default headers values
func NewGetAPIAgentsRunningTargetNameRootDomainNameSubdomainNameOK() *GetAPIAgentsRunningTargetNameRootDomainNameSubdomainNameOK {
	return &GetAPIAgentsRunningTargetNameRootDomainNameSubdomainNameOK{}
}

/* GetAPIAgentsRunningTargetNameRootDomainNameSubdomainNameOK describes a response with status code 200, with default header values.

Success
*/
type GetAPIAgentsRunningTargetNameRootDomainNameSubdomainNameOK struct {
}

func (o *GetAPIAgentsRunningTargetNameRootDomainNameSubdomainNameOK) Error() string {
	return fmt.Sprintf("[GET /api/Agents/running/{targetName}/{rootDomainName}/{subdomainName}][%d] getApiAgentsRunningTargetNameRootDomainNameSubdomainNameOK ", 200)
}

func (o *GetAPIAgentsRunningTargetNameRootDomainNameSubdomainNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
