// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIAgentsMarketplaceParams creates a new GetAPIAgentsMarketplaceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIAgentsMarketplaceParams() *GetAPIAgentsMarketplaceParams {
	return &GetAPIAgentsMarketplaceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIAgentsMarketplaceParamsWithTimeout creates a new GetAPIAgentsMarketplaceParams object
// with the ability to set a timeout on a request.
func NewGetAPIAgentsMarketplaceParamsWithTimeout(timeout time.Duration) *GetAPIAgentsMarketplaceParams {
	return &GetAPIAgentsMarketplaceParams{
		timeout: timeout,
	}
}

// NewGetAPIAgentsMarketplaceParamsWithContext creates a new GetAPIAgentsMarketplaceParams object
// with the ability to set a context for a request.
func NewGetAPIAgentsMarketplaceParamsWithContext(ctx context.Context) *GetAPIAgentsMarketplaceParams {
	return &GetAPIAgentsMarketplaceParams{
		Context: ctx,
	}
}

// NewGetAPIAgentsMarketplaceParamsWithHTTPClient creates a new GetAPIAgentsMarketplaceParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIAgentsMarketplaceParamsWithHTTPClient(client *http.Client) *GetAPIAgentsMarketplaceParams {
	return &GetAPIAgentsMarketplaceParams{
		HTTPClient: client,
	}
}

/* GetAPIAgentsMarketplaceParams contains all the parameters to send to the API endpoint
   for the get API agents marketplace operation.

   Typically these are written to a http.Request.
*/
type GetAPIAgentsMarketplaceParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API agents marketplace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIAgentsMarketplaceParams) WithDefaults() *GetAPIAgentsMarketplaceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API agents marketplace params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIAgentsMarketplaceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API agents marketplace params
func (o *GetAPIAgentsMarketplaceParams) WithTimeout(timeout time.Duration) *GetAPIAgentsMarketplaceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API agents marketplace params
func (o *GetAPIAgentsMarketplaceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API agents marketplace params
func (o *GetAPIAgentsMarketplaceParams) WithContext(ctx context.Context) *GetAPIAgentsMarketplaceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API agents marketplace params
func (o *GetAPIAgentsMarketplaceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API agents marketplace params
func (o *GetAPIAgentsMarketplaceParams) WithHTTPClient(client *http.Client) *GetAPIAgentsMarketplaceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API agents marketplace params
func (o *GetAPIAgentsMarketplaceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIAgentsMarketplaceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
