// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIAgentsMarketplaceReader is a Reader for the GetAPIAgentsMarketplace structure.
type GetAPIAgentsMarketplaceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIAgentsMarketplaceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIAgentsMarketplaceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIAgentsMarketplaceOK creates a GetAPIAgentsMarketplaceOK with default headers values
func NewGetAPIAgentsMarketplaceOK() *GetAPIAgentsMarketplaceOK {
	return &GetAPIAgentsMarketplaceOK{}
}

/* GetAPIAgentsMarketplaceOK describes a response with status code 200, with default header values.

Success
*/
type GetAPIAgentsMarketplaceOK struct {
}

func (o *GetAPIAgentsMarketplaceOK) Error() string {
	return fmt.Sprintf("[GET /api/Agents/marketplace][%d] getApiAgentsMarketplaceOK ", 200)
}

func (o *GetAPIAgentsMarketplaceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
