// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hiddengearz/reconness-cli/sdk/models"
)

// NewPostAPIAgentsStopParams creates a new PostAPIAgentsStopParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIAgentsStopParams() *PostAPIAgentsStopParams {
	return &PostAPIAgentsStopParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIAgentsStopParamsWithTimeout creates a new PostAPIAgentsStopParams object
// with the ability to set a timeout on a request.
func NewPostAPIAgentsStopParamsWithTimeout(timeout time.Duration) *PostAPIAgentsStopParams {
	return &PostAPIAgentsStopParams{
		timeout: timeout,
	}
}

// NewPostAPIAgentsStopParamsWithContext creates a new PostAPIAgentsStopParams object
// with the ability to set a context for a request.
func NewPostAPIAgentsStopParamsWithContext(ctx context.Context) *PostAPIAgentsStopParams {
	return &PostAPIAgentsStopParams{
		Context: ctx,
	}
}

// NewPostAPIAgentsStopParamsWithHTTPClient creates a new PostAPIAgentsStopParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIAgentsStopParamsWithHTTPClient(client *http.Client) *PostAPIAgentsStopParams {
	return &PostAPIAgentsStopParams{
		HTTPClient: client,
	}
}

/* PostAPIAgentsStopParams contains all the parameters to send to the API endpoint
   for the post API agents stop operation.

   Typically these are written to a http.Request.
*/
type PostAPIAgentsStopParams struct {

	// Body.
	Body *models.AgentRunnerDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API agents stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIAgentsStopParams) WithDefaults() *PostAPIAgentsStopParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API agents stop params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIAgentsStopParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API agents stop params
func (o *PostAPIAgentsStopParams) WithTimeout(timeout time.Duration) *PostAPIAgentsStopParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API agents stop params
func (o *PostAPIAgentsStopParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API agents stop params
func (o *PostAPIAgentsStopParams) WithContext(ctx context.Context) *PostAPIAgentsStopParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API agents stop params
func (o *PostAPIAgentsStopParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API agents stop params
func (o *PostAPIAgentsStopParams) WithHTTPClient(client *http.Client) *PostAPIAgentsStopParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API agents stop params
func (o *PostAPIAgentsStopParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API agents stop params
func (o *PostAPIAgentsStopParams) WithBody(body *models.AgentRunnerDto) *PostAPIAgentsStopParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API agents stop params
func (o *PostAPIAgentsStopParams) SetBody(body *models.AgentRunnerDto) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIAgentsStopParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
