// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostAPIAgentsStopReader is a Reader for the PostAPIAgentsStop structure.
type PostAPIAgentsStopReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIAgentsStopReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIAgentsStopOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPIAgentsStopOK creates a PostAPIAgentsStopOK with default headers values
func NewPostAPIAgentsStopOK() *PostAPIAgentsStopOK {
	return &PostAPIAgentsStopOK{}
}

/* PostAPIAgentsStopOK describes a response with status code 200, with default header values.

Success
*/
type PostAPIAgentsStopOK struct {
}

func (o *PostAPIAgentsStopOK) Error() string {
	return fmt.Sprintf("[POST /api/Agents/stop][%d] postApiAgentsStopOK ", 200)
}

func (o *PostAPIAgentsStopOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
