// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hiddengearz/reconness-cli/sdk/models"
)

// NewPostAPIAgentsDebugParams creates a new PostAPIAgentsDebugParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIAgentsDebugParams() *PostAPIAgentsDebugParams {
	return &PostAPIAgentsDebugParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIAgentsDebugParamsWithTimeout creates a new PostAPIAgentsDebugParams object
// with the ability to set a timeout on a request.
func NewPostAPIAgentsDebugParamsWithTimeout(timeout time.Duration) *PostAPIAgentsDebugParams {
	return &PostAPIAgentsDebugParams{
		timeout: timeout,
	}
}

// NewPostAPIAgentsDebugParamsWithContext creates a new PostAPIAgentsDebugParams object
// with the ability to set a context for a request.
func NewPostAPIAgentsDebugParamsWithContext(ctx context.Context) *PostAPIAgentsDebugParams {
	return &PostAPIAgentsDebugParams{
		Context: ctx,
	}
}

// NewPostAPIAgentsDebugParamsWithHTTPClient creates a new PostAPIAgentsDebugParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIAgentsDebugParamsWithHTTPClient(client *http.Client) *PostAPIAgentsDebugParams {
	return &PostAPIAgentsDebugParams{
		HTTPClient: client,
	}
}

/* PostAPIAgentsDebugParams contains all the parameters to send to the API endpoint
   for the post API agents debug operation.

   Typically these are written to a http.Request.
*/
type PostAPIAgentsDebugParams struct {

	// Body.
	Body *models.AgentDebugDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API agents debug params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIAgentsDebugParams) WithDefaults() *PostAPIAgentsDebugParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API agents debug params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIAgentsDebugParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API agents debug params
func (o *PostAPIAgentsDebugParams) WithTimeout(timeout time.Duration) *PostAPIAgentsDebugParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API agents debug params
func (o *PostAPIAgentsDebugParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API agents debug params
func (o *PostAPIAgentsDebugParams) WithContext(ctx context.Context) *PostAPIAgentsDebugParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API agents debug params
func (o *PostAPIAgentsDebugParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API agents debug params
func (o *PostAPIAgentsDebugParams) WithHTTPClient(client *http.Client) *PostAPIAgentsDebugParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API agents debug params
func (o *PostAPIAgentsDebugParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API agents debug params
func (o *PostAPIAgentsDebugParams) WithBody(body *models.AgentDebugDto) *PostAPIAgentsDebugParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API agents debug params
func (o *PostAPIAgentsDebugParams) SetBody(body *models.AgentDebugDto) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIAgentsDebugParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
