// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hiddengearz/reconness-cli/sdk/models"
)

// NewPostAPIAgentsInstallParams creates a new PostAPIAgentsInstallParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIAgentsInstallParams() *PostAPIAgentsInstallParams {
	return &PostAPIAgentsInstallParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIAgentsInstallParamsWithTimeout creates a new PostAPIAgentsInstallParams object
// with the ability to set a timeout on a request.
func NewPostAPIAgentsInstallParamsWithTimeout(timeout time.Duration) *PostAPIAgentsInstallParams {
	return &PostAPIAgentsInstallParams{
		timeout: timeout,
	}
}

// NewPostAPIAgentsInstallParamsWithContext creates a new PostAPIAgentsInstallParams object
// with the ability to set a context for a request.
func NewPostAPIAgentsInstallParamsWithContext(ctx context.Context) *PostAPIAgentsInstallParams {
	return &PostAPIAgentsInstallParams{
		Context: ctx,
	}
}

// NewPostAPIAgentsInstallParamsWithHTTPClient creates a new PostAPIAgentsInstallParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIAgentsInstallParamsWithHTTPClient(client *http.Client) *PostAPIAgentsInstallParams {
	return &PostAPIAgentsInstallParams{
		HTTPClient: client,
	}
}

/* PostAPIAgentsInstallParams contains all the parameters to send to the API endpoint
   for the post API agents install operation.

   Typically these are written to a http.Request.
*/
type PostAPIAgentsInstallParams struct {

	// Body.
	Body *models.AgentMarketplaceDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API agents install params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIAgentsInstallParams) WithDefaults() *PostAPIAgentsInstallParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API agents install params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIAgentsInstallParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API agents install params
func (o *PostAPIAgentsInstallParams) WithTimeout(timeout time.Duration) *PostAPIAgentsInstallParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API agents install params
func (o *PostAPIAgentsInstallParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API agents install params
func (o *PostAPIAgentsInstallParams) WithContext(ctx context.Context) *PostAPIAgentsInstallParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API agents install params
func (o *PostAPIAgentsInstallParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API agents install params
func (o *PostAPIAgentsInstallParams) WithHTTPClient(client *http.Client) *PostAPIAgentsInstallParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API agents install params
func (o *PostAPIAgentsInstallParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API agents install params
func (o *PostAPIAgentsInstallParams) WithBody(body *models.AgentMarketplaceDto) *PostAPIAgentsInstallParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API agents install params
func (o *PostAPIAgentsInstallParams) SetBody(body *models.AgentMarketplaceDto) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIAgentsInstallParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
