// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PutAPIAgentsIDReader is a Reader for the PutAPIAgentsID structure.
type PutAPIAgentsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PutAPIAgentsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPutAPIAgentsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPutAPIAgentsIDOK creates a PutAPIAgentsIDOK with default headers values
func NewPutAPIAgentsIDOK() *PutAPIAgentsIDOK {
	return &PutAPIAgentsIDOK{}
}

/* PutAPIAgentsIDOK describes a response with status code 200, with default header values.

Success
*/
type PutAPIAgentsIDOK struct {
}

func (o *PutAPIAgentsIDOK) Error() string {
	return fmt.Sprintf("[PUT /api/Agents/{id}][%d] putApiAgentsIdOK ", 200)
}

func (o *PutAPIAgentsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
