// Code generated by go-swagger; DO NOT EDIT.

package targets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPITargetsParams creates a new GetAPITargetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPITargetsParams() *GetAPITargetsParams {
	return &GetAPITargetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPITargetsParamsWithTimeout creates a new GetAPITargetsParams object
// with the ability to set a timeout on a request.
func NewGetAPITargetsParamsWithTimeout(timeout time.Duration) *GetAPITargetsParams {
	return &GetAPITargetsParams{
		timeout: timeout,
	}
}

// NewGetAPITargetsParamsWithContext creates a new GetAPITargetsParams object
// with the ability to set a context for a request.
func NewGetAPITargetsParamsWithContext(ctx context.Context) *GetAPITargetsParams {
	return &GetAPITargetsParams{
		Context: ctx,
	}
}

// NewGetAPITargetsParamsWithHTTPClient creates a new GetAPITargetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPITargetsParamsWithHTTPClient(client *http.Client) *GetAPITargetsParams {
	return &GetAPITargetsParams{
		HTTPClient: client,
	}
}

/* GetAPITargetsParams contains all the parameters to send to the API endpoint
   for the get API targets operation.

   Typically these are written to a http.Request.
*/
type GetAPITargetsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API targets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPITargetsParams) WithDefaults() *GetAPITargetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API targets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPITargetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API targets params
func (o *GetAPITargetsParams) WithTimeout(timeout time.Duration) *GetAPITargetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API targets params
func (o *GetAPITargetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API targets params
func (o *GetAPITargetsParams) WithContext(ctx context.Context) *GetAPITargetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API targets params
func (o *GetAPITargetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API targets params
func (o *GetAPITargetsParams) WithHTTPClient(client *http.Client) *GetAPITargetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API targets params
func (o *GetAPITargetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPITargetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
