// Code generated by go-swagger; DO NOT EDIT.

package targets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostAPITargetsImportRootDomainTargetNameReader is a Reader for the PostAPITargetsImportRootDomainTargetName structure.
type PostAPITargetsImportRootDomainTargetNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPITargetsImportRootDomainTargetNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPITargetsImportRootDomainTargetNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPITargetsImportRootDomainTargetNameOK creates a PostAPITargetsImportRootDomainTargetNameOK with default headers values
func NewPostAPITargetsImportRootDomainTargetNameOK() *PostAPITargetsImportRootDomainTargetNameOK {
	return &PostAPITargetsImportRootDomainTargetNameOK{}
}

/* PostAPITargetsImportRootDomainTargetNameOK describes a response with status code 200, with default header values.

Success
*/
type PostAPITargetsImportRootDomainTargetNameOK struct {
}

func (o *PostAPITargetsImportRootDomainTargetNameOK) Error() string {
	return fmt.Sprintf("[POST /api/Targets/importRootDomain/{targetName}][%d] postApiTargetsImportRootDomainTargetNameOK ", 200)
}

func (o *PostAPITargetsImportRootDomainTargetNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
