// Code generated by go-swagger; DO NOT EDIT.

package targets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hiddengearz/reconness-cli/sdk/models"
)

// NewPostAPITargetsParams creates a new PostAPITargetsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPITargetsParams() *PostAPITargetsParams {
	return &PostAPITargetsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPITargetsParamsWithTimeout creates a new PostAPITargetsParams object
// with the ability to set a timeout on a request.
func NewPostAPITargetsParamsWithTimeout(timeout time.Duration) *PostAPITargetsParams {
	return &PostAPITargetsParams{
		timeout: timeout,
	}
}

// NewPostAPITargetsParamsWithContext creates a new PostAPITargetsParams object
// with the ability to set a context for a request.
func NewPostAPITargetsParamsWithContext(ctx context.Context) *PostAPITargetsParams {
	return &PostAPITargetsParams{
		Context: ctx,
	}
}

// NewPostAPITargetsParamsWithHTTPClient creates a new PostAPITargetsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPITargetsParamsWithHTTPClient(client *http.Client) *PostAPITargetsParams {
	return &PostAPITargetsParams{
		HTTPClient: client,
	}
}

/* PostAPITargetsParams contains all the parameters to send to the API endpoint
   for the post API targets operation.

   Typically these are written to a http.Request.
*/
type PostAPITargetsParams struct {

	// Body.
	Body *models.TargetDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API targets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPITargetsParams) WithDefaults() *PostAPITargetsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API targets params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPITargetsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API targets params
func (o *PostAPITargetsParams) WithTimeout(timeout time.Duration) *PostAPITargetsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API targets params
func (o *PostAPITargetsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API targets params
func (o *PostAPITargetsParams) WithContext(ctx context.Context) *PostAPITargetsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API targets params
func (o *PostAPITargetsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API targets params
func (o *PostAPITargetsParams) WithHTTPClient(client *http.Client) *PostAPITargetsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API targets params
func (o *PostAPITargetsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API targets params
func (o *PostAPITargetsParams) WithBody(body *models.TargetDto) *PostAPITargetsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API targets params
func (o *PostAPITargetsParams) SetBody(body *models.TargetDto) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPITargetsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
