// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AccountLogFileDto account log file dto
//
// swagger:model AccountLogFileDto
type AccountLogFileDto struct {

	// log file selected
	LogFileSelected *string `json:"logFileSelected,omitempty"`
}

// Validate validates this account log file dto
func (m *AccountLogFileDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this account log file dto based on context it is used
func (m *AccountLogFileDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AccountLogFileDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountLogFileDto) UnmarshalBinary(b []byte) error {
	var res AccountLogFileDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
