// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AgentMarketplaceDto agent marketplace dto
//
// swagger:model AgentMarketplaceDto
type AgentMarketplaceDto struct {

	// category
	Category *string `json:"category,omitempty"`

	// command
	Command *string `json:"command,omitempty"`

	// is by directory
	IsByDirectory bool `json:"isByDirectory,omitempty"`

	// is by resource
	IsByResource bool `json:"isByResource,omitempty"`

	// is by root domain
	IsByRootDomain bool `json:"isByRootDomain,omitempty"`

	// is by subdomain
	IsBySubdomain bool `json:"isBySubdomain,omitempty"`

	// is by target
	IsByTarget bool `json:"isByTarget,omitempty"`

	// name
	Name *string `json:"name,omitempty"`

	// repository
	Repository *string `json:"repository,omitempty"`

	// script Url
	ScriptURL *string `json:"scriptUrl,omitempty"`
}

// Validate validates this agent marketplace dto
func (m *AgentMarketplaceDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this agent marketplace dto based on context it is used
func (m *AgentMarketplaceDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AgentMarketplaceDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgentMarketplaceDto) UnmarshalBinary(b []byte) error {
	var res AgentMarketplaceDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
