// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AgentRunnerDto agent runner dto
//
// swagger:model AgentRunnerDto
type AgentRunnerDto struct {

	// activate notification
	ActivateNotification bool `json:"activateNotification,omitempty"`

	// agent
	Agent *string `json:"agent,omitempty"`

	// command
	Command *string `json:"command,omitempty"`

	// root domain
	RootDomain *string `json:"rootDomain,omitempty"`

	// subdomain
	Subdomain *string `json:"subdomain,omitempty"`

	// target
	Target *string `json:"target,omitempty"`
}

// Validate validates this agent runner dto
func (m *AgentRunnerDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this agent runner dto based on context it is used
func (m *AgentRunnerDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AgentRunnerDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgentRunnerDto) UnmarshalBinary(b []byte) error {
	var res AgentRunnerDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
