// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AgentDebugDto agent debug dto
//
// swagger:model AgentDebugDto
type AgentDebugDto struct {

	// script
	Script *string `json:"script,omitempty"`

	// terminal output
	TerminalOutput *string `json:"terminalOutput,omitempty"`
}

// Validate validates this agent debug dto
func (m *AgentDebugDto) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this agent debug dto based on context it is used
func (m *AgentDebugDto) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AgentDebugDto) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AgentDebugDto) UnmarshalBinary(b []byte) error {
	var res AgentDebugDto
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
