// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CredentialsViewModel credentials view model
//
// swagger:model CredentialsViewModel
type CredentialsViewModel struct {

	// password
	Password *string `json:"password,omitempty"`

	// user name
	UserName *string `json:"userName,omitempty"`
}

// Validate validates this credentials view model
func (m *CredentialsViewModel) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this credentials view model based on context it is used
func (m *CredentialsViewModel) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CredentialsViewModel) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CredentialsViewModel) UnmarshalBinary(b []byte) error {
	var res CredentialsViewModel
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
