// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIAccountsCurrentVersionParams creates a new GetAPIAccountsCurrentVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIAccountsCurrentVersionParams() *GetAPIAccountsCurrentVersionParams {
	return &GetAPIAccountsCurrentVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIAccountsCurrentVersionParamsWithTimeout creates a new GetAPIAccountsCurrentVersionParams object
// with the ability to set a timeout on a request.
func NewGetAPIAccountsCurrentVersionParamsWithTimeout(timeout time.Duration) *GetAPIAccountsCurrentVersionParams {
	return &GetAPIAccountsCurrentVersionParams{
		timeout: timeout,
	}
}

// NewGetAPIAccountsCurrentVersionParamsWithContext creates a new GetAPIAccountsCurrentVersionParams object
// with the ability to set a context for a request.
func NewGetAPIAccountsCurrentVersionParamsWithContext(ctx context.Context) *GetAPIAccountsCurrentVersionParams {
	return &GetAPIAccountsCurrentVersionParams{
		Context: ctx,
	}
}

// NewGetAPIAccountsCurrentVersionParamsWithHTTPClient creates a new GetAPIAccountsCurrentVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIAccountsCurrentVersionParamsWithHTTPClient(client *http.Client) *GetAPIAccountsCurrentVersionParams {
	return &GetAPIAccountsCurrentVersionParams{
		HTTPClient: client,
	}
}

/* GetAPIAccountsCurrentVersionParams contains all the parameters to send to the API endpoint
   for the get API accounts current version operation.

   Typically these are written to a http.Request.
*/
type GetAPIAccountsCurrentVersionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API accounts current version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIAccountsCurrentVersionParams) WithDefaults() *GetAPIAccountsCurrentVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API accounts current version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIAccountsCurrentVersionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API accounts current version params
func (o *GetAPIAccountsCurrentVersionParams) WithTimeout(timeout time.Duration) *GetAPIAccountsCurrentVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API accounts current version params
func (o *GetAPIAccountsCurrentVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API accounts current version params
func (o *GetAPIAccountsCurrentVersionParams) WithContext(ctx context.Context) *GetAPIAccountsCurrentVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API accounts current version params
func (o *GetAPIAccountsCurrentVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API accounts current version params
func (o *GetAPIAccountsCurrentVersionParams) WithHTTPClient(client *http.Client) *GetAPIAccountsCurrentVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API accounts current version params
func (o *GetAPIAccountsCurrentVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIAccountsCurrentVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
