// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIAccountsReadLogfileLogFileSelectedParams creates a new GetAPIAccountsReadLogfileLogFileSelectedParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIAccountsReadLogfileLogFileSelectedParams() *GetAPIAccountsReadLogfileLogFileSelectedParams {
	return &GetAPIAccountsReadLogfileLogFileSelectedParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIAccountsReadLogfileLogFileSelectedParamsWithTimeout creates a new GetAPIAccountsReadLogfileLogFileSelectedParams object
// with the ability to set a timeout on a request.
func NewGetAPIAccountsReadLogfileLogFileSelectedParamsWithTimeout(timeout time.Duration) *GetAPIAccountsReadLogfileLogFileSelectedParams {
	return &GetAPIAccountsReadLogfileLogFileSelectedParams{
		timeout: timeout,
	}
}

// NewGetAPIAccountsReadLogfileLogFileSelectedParamsWithContext creates a new GetAPIAccountsReadLogfileLogFileSelectedParams object
// with the ability to set a context for a request.
func NewGetAPIAccountsReadLogfileLogFileSelectedParamsWithContext(ctx context.Context) *GetAPIAccountsReadLogfileLogFileSelectedParams {
	return &GetAPIAccountsReadLogfileLogFileSelectedParams{
		Context: ctx,
	}
}

// NewGetAPIAccountsReadLogfileLogFileSelectedParamsWithHTTPClient creates a new GetAPIAccountsReadLogfileLogFileSelectedParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIAccountsReadLogfileLogFileSelectedParamsWithHTTPClient(client *http.Client) *GetAPIAccountsReadLogfileLogFileSelectedParams {
	return &GetAPIAccountsReadLogfileLogFileSelectedParams{
		HTTPClient: client,
	}
}

/* GetAPIAccountsReadLogfileLogFileSelectedParams contains all the parameters to send to the API endpoint
   for the get API accounts read logfile log file selected operation.

   Typically these are written to a http.Request.
*/
type GetAPIAccountsReadLogfileLogFileSelectedParams struct {

	// LogFileSelected.
	LogFileSelected string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API accounts read logfile log file selected params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIAccountsReadLogfileLogFileSelectedParams) WithDefaults() *GetAPIAccountsReadLogfileLogFileSelectedParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API accounts read logfile log file selected params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIAccountsReadLogfileLogFileSelectedParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API accounts read logfile log file selected params
func (o *GetAPIAccountsReadLogfileLogFileSelectedParams) WithTimeout(timeout time.Duration) *GetAPIAccountsReadLogfileLogFileSelectedParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API accounts read logfile log file selected params
func (o *GetAPIAccountsReadLogfileLogFileSelectedParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API accounts read logfile log file selected params
func (o *GetAPIAccountsReadLogfileLogFileSelectedParams) WithContext(ctx context.Context) *GetAPIAccountsReadLogfileLogFileSelectedParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API accounts read logfile log file selected params
func (o *GetAPIAccountsReadLogfileLogFileSelectedParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API accounts read logfile log file selected params
func (o *GetAPIAccountsReadLogfileLogFileSelectedParams) WithHTTPClient(client *http.Client) *GetAPIAccountsReadLogfileLogFileSelectedParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API accounts read logfile log file selected params
func (o *GetAPIAccountsReadLogfileLogFileSelectedParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLogFileSelected adds the logFileSelected to the get API accounts read logfile log file selected params
func (o *GetAPIAccountsReadLogfileLogFileSelectedParams) WithLogFileSelected(logFileSelected string) *GetAPIAccountsReadLogfileLogFileSelectedParams {
	o.SetLogFileSelected(logFileSelected)
	return o
}

// SetLogFileSelected adds the logFileSelected to the get API accounts read logfile log file selected params
func (o *GetAPIAccountsReadLogfileLogFileSelectedParams) SetLogFileSelected(logFileSelected string) {
	o.LogFileSelected = logFileSelected
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIAccountsReadLogfileLogFileSelectedParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param logFileSelected
	if err := r.SetPathParam("logFileSelected", o.LogFileSelected); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
