// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIAccountsNotificationReader is a Reader for the GetAPIAccountsNotification structure.
type GetAPIAccountsNotificationReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIAccountsNotificationReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIAccountsNotificationOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIAccountsNotificationOK creates a GetAPIAccountsNotificationOK with default headers values
func NewGetAPIAccountsNotificationOK() *GetAPIAccountsNotificationOK {
	return &GetAPIAccountsNotificationOK{}
}

/* GetAPIAccountsNotificationOK describes a response with status code 200, with default header values.

Success
*/
type GetAPIAccountsNotificationOK struct {
}

func (o *GetAPIAccountsNotificationOK) Error() string {
	return fmt.Sprintf("[GET /api/Accounts/notification][%d] getApiAccountsNotificationOK ", 200)
}

func (o *GetAPIAccountsNotificationOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
