// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIAccountsLatestVersionReader is a Reader for the GetAPIAccountsLatestVersion structure.
type GetAPIAccountsLatestVersionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIAccountsLatestVersionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIAccountsLatestVersionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIAccountsLatestVersionOK creates a GetAPIAccountsLatestVersionOK with default headers values
func NewGetAPIAccountsLatestVersionOK() *GetAPIAccountsLatestVersionOK {
	return &GetAPIAccountsLatestVersionOK{}
}

/* GetAPIAccountsLatestVersionOK describes a response with status code 200, with default header values.

Success
*/
type GetAPIAccountsLatestVersionOK struct {
}

func (o *GetAPIAccountsLatestVersionOK) Error() string {
	return fmt.Sprintf("[GET /api/Accounts/latestVersion][%d] getApiAccountsLatestVersionOK ", 200)
}

func (o *GetAPIAccountsLatestVersionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
