// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIAccountsLatestVersionParams creates a new GetAPIAccountsLatestVersionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIAccountsLatestVersionParams() *GetAPIAccountsLatestVersionParams {
	return &GetAPIAccountsLatestVersionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIAccountsLatestVersionParamsWithTimeout creates a new GetAPIAccountsLatestVersionParams object
// with the ability to set a timeout on a request.
func NewGetAPIAccountsLatestVersionParamsWithTimeout(timeout time.Duration) *GetAPIAccountsLatestVersionParams {
	return &GetAPIAccountsLatestVersionParams{
		timeout: timeout,
	}
}

// NewGetAPIAccountsLatestVersionParamsWithContext creates a new GetAPIAccountsLatestVersionParams object
// with the ability to set a context for a request.
func NewGetAPIAccountsLatestVersionParamsWithContext(ctx context.Context) *GetAPIAccountsLatestVersionParams {
	return &GetAPIAccountsLatestVersionParams{
		Context: ctx,
	}
}

// NewGetAPIAccountsLatestVersionParamsWithHTTPClient creates a new GetAPIAccountsLatestVersionParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIAccountsLatestVersionParamsWithHTTPClient(client *http.Client) *GetAPIAccountsLatestVersionParams {
	return &GetAPIAccountsLatestVersionParams{
		HTTPClient: client,
	}
}

/* GetAPIAccountsLatestVersionParams contains all the parameters to send to the API endpoint
   for the get API accounts latest version operation.

   Typically these are written to a http.Request.
*/
type GetAPIAccountsLatestVersionParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API accounts latest version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIAccountsLatestVersionParams) WithDefaults() *GetAPIAccountsLatestVersionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API accounts latest version params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIAccountsLatestVersionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API accounts latest version params
func (o *GetAPIAccountsLatestVersionParams) WithTimeout(timeout time.Duration) *GetAPIAccountsLatestVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API accounts latest version params
func (o *GetAPIAccountsLatestVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API accounts latest version params
func (o *GetAPIAccountsLatestVersionParams) WithContext(ctx context.Context) *GetAPIAccountsLatestVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API accounts latest version params
func (o *GetAPIAccountsLatestVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API accounts latest version params
func (o *GetAPIAccountsLatestVersionParams) WithHTTPClient(client *http.Client) *GetAPIAccountsLatestVersionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API accounts latest version params
func (o *GetAPIAccountsLatestVersionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIAccountsLatestVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
