// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIAccountsLogfilesReader is a Reader for the GetAPIAccountsLogfiles structure.
type GetAPIAccountsLogfilesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIAccountsLogfilesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIAccountsLogfilesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIAccountsLogfilesOK creates a GetAPIAccountsLogfilesOK with default headers values
func NewGetAPIAccountsLogfilesOK() *GetAPIAccountsLogfilesOK {
	return &GetAPIAccountsLogfilesOK{}
}

/* GetAPIAccountsLogfilesOK describes a response with status code 200, with default header values.

Success
*/
type GetAPIAccountsLogfilesOK struct {
}

func (o *GetAPIAccountsLogfilesOK) Error() string {
	return fmt.Sprintf("[GET /api/Accounts/logfiles][%d] getApiAccountsLogfilesOK ", 200)
}

func (o *GetAPIAccountsLogfilesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
