// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/hiddengearz/reconness-cli/sdk/models"
)

// NewPostAPIAccountsCleanLogfileParams creates a new PostAPIAccountsCleanLogfileParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIAccountsCleanLogfileParams() *PostAPIAccountsCleanLogfileParams {
	return &PostAPIAccountsCleanLogfileParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIAccountsCleanLogfileParamsWithTimeout creates a new PostAPIAccountsCleanLogfileParams object
// with the ability to set a timeout on a request.
func NewPostAPIAccountsCleanLogfileParamsWithTimeout(timeout time.Duration) *PostAPIAccountsCleanLogfileParams {
	return &PostAPIAccountsCleanLogfileParams{
		timeout: timeout,
	}
}

// NewPostAPIAccountsCleanLogfileParamsWithContext creates a new PostAPIAccountsCleanLogfileParams object
// with the ability to set a context for a request.
func NewPostAPIAccountsCleanLogfileParamsWithContext(ctx context.Context) *PostAPIAccountsCleanLogfileParams {
	return &PostAPIAccountsCleanLogfileParams{
		Context: ctx,
	}
}

// NewPostAPIAccountsCleanLogfileParamsWithHTTPClient creates a new PostAPIAccountsCleanLogfileParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIAccountsCleanLogfileParamsWithHTTPClient(client *http.Client) *PostAPIAccountsCleanLogfileParams {
	return &PostAPIAccountsCleanLogfileParams{
		HTTPClient: client,
	}
}

/* PostAPIAccountsCleanLogfileParams contains all the parameters to send to the API endpoint
   for the post API accounts clean logfile operation.

   Typically these are written to a http.Request.
*/
type PostAPIAccountsCleanLogfileParams struct {

	// Body.
	Body *models.AccountLogFileDto

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API accounts clean logfile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIAccountsCleanLogfileParams) WithDefaults() *PostAPIAccountsCleanLogfileParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API accounts clean logfile params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIAccountsCleanLogfileParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API accounts clean logfile params
func (o *PostAPIAccountsCleanLogfileParams) WithTimeout(timeout time.Duration) *PostAPIAccountsCleanLogfileParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API accounts clean logfile params
func (o *PostAPIAccountsCleanLogfileParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API accounts clean logfile params
func (o *PostAPIAccountsCleanLogfileParams) WithContext(ctx context.Context) *PostAPIAccountsCleanLogfileParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API accounts clean logfile params
func (o *PostAPIAccountsCleanLogfileParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API accounts clean logfile params
func (o *PostAPIAccountsCleanLogfileParams) WithHTTPClient(client *http.Client) *PostAPIAccountsCleanLogfileParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API accounts clean logfile params
func (o *PostAPIAccountsCleanLogfileParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API accounts clean logfile params
func (o *PostAPIAccountsCleanLogfileParams) WithBody(body *models.AccountLogFileDto) *PostAPIAccountsCleanLogfileParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API accounts clean logfile params
func (o *PostAPIAccountsCleanLogfileParams) SetBody(body *models.AccountLogFileDto) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIAccountsCleanLogfileParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
