// Code generated by go-swagger; DO NOT EDIT.

package references

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIReferencesIDParams creates a new DeleteAPIReferencesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIReferencesIDParams() *DeleteAPIReferencesIDParams {
	return &DeleteAPIReferencesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIReferencesIDParamsWithTimeout creates a new DeleteAPIReferencesIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIReferencesIDParamsWithTimeout(timeout time.Duration) *DeleteAPIReferencesIDParams {
	return &DeleteAPIReferencesIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPIReferencesIDParamsWithContext creates a new DeleteAPIReferencesIDParams object
// with the ability to set a context for a request.
func NewDeleteAPIReferencesIDParamsWithContext(ctx context.Context) *DeleteAPIReferencesIDParams {
	return &DeleteAPIReferencesIDParams{
		Context: ctx,
	}
}

// NewDeleteAPIReferencesIDParamsWithHTTPClient creates a new DeleteAPIReferencesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIReferencesIDParamsWithHTTPClient(client *http.Client) *DeleteAPIReferencesIDParams {
	return &DeleteAPIReferencesIDParams{
		HTTPClient: client,
	}
}

/* DeleteAPIReferencesIDParams contains all the parameters to send to the API endpoint
   for the delete API references ID operation.

   Typically these are written to a http.Request.
*/
type DeleteAPIReferencesIDParams struct {

	// ID.
	//
	// Format: uuid
	ID strfmt.UUID

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API references ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIReferencesIDParams) WithDefaults() *DeleteAPIReferencesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API references ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIReferencesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API references ID params
func (o *DeleteAPIReferencesIDParams) WithTimeout(timeout time.Duration) *DeleteAPIReferencesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API references ID params
func (o *DeleteAPIReferencesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API references ID params
func (o *DeleteAPIReferencesIDParams) WithContext(ctx context.Context) *DeleteAPIReferencesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API references ID params
func (o *DeleteAPIReferencesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API references ID params
func (o *DeleteAPIReferencesIDParams) WithHTTPClient(client *http.Client) *DeleteAPIReferencesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API references ID params
func (o *DeleteAPIReferencesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete API references ID params
func (o *DeleteAPIReferencesIDParams) WithID(id strfmt.UUID) *DeleteAPIReferencesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete API references ID params
func (o *DeleteAPIReferencesIDParams) SetID(id strfmt.UUID) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIReferencesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID.String()); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
