// Code generated by go-swagger; DO NOT EDIT.

package references

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIReferencesReader is a Reader for the GetAPIReferences structure.
type GetAPIReferencesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIReferencesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIReferencesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGetAPIReferencesOK creates a GetAPIReferencesOK with default headers values
func NewGetAPIReferencesOK() *GetAPIReferencesOK {
	return &GetAPIReferencesOK{}
}

/* GetAPIReferencesOK describes a response with status code 200, with default header values.

Success
*/
type GetAPIReferencesOK struct {
}

func (o *GetAPIReferencesOK) Error() string {
	return fmt.Sprintf("[GET /api/References][%d] getApiReferencesOK ", 200)
}

func (o *GetAPIReferencesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
