// Code generated by go-swagger; DO NOT EDIT.

package references

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIReferencesCategoriesParams creates a new GetAPIReferencesCategoriesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIReferencesCategoriesParams() *GetAPIReferencesCategoriesParams {
	return &GetAPIReferencesCategoriesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIReferencesCategoriesParamsWithTimeout creates a new GetAPIReferencesCategoriesParams object
// with the ability to set a timeout on a request.
func NewGetAPIReferencesCategoriesParamsWithTimeout(timeout time.Duration) *GetAPIReferencesCategoriesParams {
	return &GetAPIReferencesCategoriesParams{
		timeout: timeout,
	}
}

// NewGetAPIReferencesCategoriesParamsWithContext creates a new GetAPIReferencesCategoriesParams object
// with the ability to set a context for a request.
func NewGetAPIReferencesCategoriesParamsWithContext(ctx context.Context) *GetAPIReferencesCategoriesParams {
	return &GetAPIReferencesCategoriesParams{
		Context: ctx,
	}
}

// NewGetAPIReferencesCategoriesParamsWithHTTPClient creates a new GetAPIReferencesCategoriesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIReferencesCategoriesParamsWithHTTPClient(client *http.Client) *GetAPIReferencesCategoriesParams {
	return &GetAPIReferencesCategoriesParams{
		HTTPClient: client,
	}
}

/* GetAPIReferencesCategoriesParams contains all the parameters to send to the API endpoint
   for the get API references categories operation.

   Typically these are written to a http.Request.
*/
type GetAPIReferencesCategoriesParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API references categories params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIReferencesCategoriesParams) WithDefaults() *GetAPIReferencesCategoriesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API references categories params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIReferencesCategoriesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API references categories params
func (o *GetAPIReferencesCategoriesParams) WithTimeout(timeout time.Duration) *GetAPIReferencesCategoriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API references categories params
func (o *GetAPIReferencesCategoriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API references categories params
func (o *GetAPIReferencesCategoriesParams) WithContext(ctx context.Context) *GetAPIReferencesCategoriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API references categories params
func (o *GetAPIReferencesCategoriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API references categories params
func (o *GetAPIReferencesCategoriesParams) WithHTTPClient(client *http.Client) *GetAPIReferencesCategoriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API references categories params
func (o *GetAPIReferencesCategoriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIReferencesCategoriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
