// Code generated by go-swagger; DO NOT EDIT.

package references

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PostAPIReferencesReader is a Reader for the PostAPIReferences structure.
type PostAPIReferencesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIReferencesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIReferencesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPostAPIReferencesOK creates a PostAPIReferencesOK with default headers values
func NewPostAPIReferencesOK() *PostAPIReferencesOK {
	return &PostAPIReferencesOK{}
}

/* PostAPIReferencesOK describes a response with status code 200, with default header values.

Success
*/
type PostAPIReferencesOK struct {
}

func (o *PostAPIReferencesOK) Error() string {
	return fmt.Sprintf("[POST /api/References][%d] postApiReferencesOK ", 200)
}

func (o *PostAPIReferencesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
